// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9uiwHilDkptQ5hvCPYNcCTkWgLZ-__E',
    appId: '1:1079285390558:web:6f192c04d0f4365ba7364f',
    messagingSenderId: '1079285390558',
    projectId: 'tradeon-stock-market',
    authDomain: 'tradeon-stock-market.firebaseapp.com',
    storageBucket: 'tradeon-stock-market.firebasestorage.app',
    measurementId: 'G-Y12ZWNZRDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvE4dcLb_IOhTk4yincvPRMa2N3n-mkz4',
    appId: '1:1079285390558:android:79cc7a441ea45afaa7364f',
    messagingSenderId: '1079285390558',
    projectId: 'tradeon-stock-market',
    storageBucket: 'tradeon-stock-market.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMfWGFAqxny-oeWoD1x_lzrDYGenw1Qk',
    appId: '1:1079285390558:ios:7dfb1522a9256120a7364f',
    messagingSenderId: '1079285390558',
    projectId: 'tradeon-stock-market',
    storageBucket: 'tradeon-stock-market.firebasestorage.app',
    iosBundleId: 'com.example.stockMarketTrackerMobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMfWGFAqxny-oeWoD1x_lzrDYGenw1Qk',
    appId: '1:1079285390558:ios:d68b91e84af0121ca7364f',
    messagingSenderId: '1079285390558',
    projectId: 'tradeon-stock-market',
    storageBucket: 'tradeon-stock-market.firebasestorage.app',
    iosBundleId: 'com.example.stockMarketTrackerMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc9uiwHilDkptQ5hvCPYNcCTkWgLZ-__E',
    appId: '1:1079285390558:web:e00207a3005164dba7364f',
    messagingSenderId: '1079285390558',
    projectId: 'tradeon-stock-market',
    authDomain: 'tradeon-stock-market.firebaseapp.com',
    storageBucket: 'tradeon-stock-market.firebasestorage.app',
    measurementId: 'G-JZCBET0TWC',
  );
}
